fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    apt:
      repo: puppetlabs/apt
    epel:
      repo: puppet/epel
    rhsm:
      repo: puppet/rhsm
    concat:
      repo: puppetlabs/concat
    vcsrepo:
      repo: puppetlabs/vcsrepo
    apache:
      repo: puppetlabs/apache
    sudo:
      repo: saz/sudo
    augeasproviders_core:
      repo: herculesteam/augeasproviders_core
    augeasproviders_shellvar:
      repo: herculesteam/augeasproviders_shellvar
    systemd:
      repo: puppet/systemd
    logrotate:
      repo: puppet/logrotate
  symlinks:
    openondemand: "#{source_dir}"
