fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    apt:
      repo: puppetlabs/apt
    epel:
      repo: puppet/epel
    rhsm:
      repo: puppet/rhsm
    concat:
      repo: puppetlabs/concat
    vcsrepo:
      repo: puppetlabs/vcsrepo
    apache:
      repo: puppetlabs/apache
    # TODO: Once something newer than 7.0.2 released
    #sudo:
    #  repo: saz/sudo
    augeasproviders_core:
      repo: puppet/augeasproviders_core
    augeasproviders_shellvar:
      repo: puppet/augeasproviders_shellvar
    systemd:
      repo: puppet/systemd
    logrotate:
      repo: puppet/logrotate
  # TODO: Remove once something newer than 7.0.2 released
  repositories:
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
  symlinks:
    openondemand: "#{source_dir}"
