---
Rakefile:
  changelog_since_tag: v1.5.0
  changelog_max_issues: 1
.github/workflows/ci.yaml:
  run_on_schedule:
    - '0 6 * * 1'
  acceptance_matrix:
      set:
        - el7
        - el8
        - el9
        - ubuntu-2004
        - ubuntu-2204
      puppet:
        - puppet7
        - puppet8
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/el7.yml:
  # TODO: Remove once using stdlib::to_yaml
  docker_env:
    - STDLIB_LOG_DEPRECATIONS=false
  default_module_install_opts:
    ignore-dependencies: ~
    force: ~
spec/acceptance/nodesets/el8.yml:
  # TODO: Remove once using stdlib::to_yaml
  docker_env:
    - STDLIB_LOG_DEPRECATIONS=false
  default_module_install_opts:
    ignore-dependencies: ~
    force: ~
spec/acceptance/nodesets/el9.yml:
  # TODO: Remove once using stdlib::to_yaml
  docker_env:
    - STDLIB_LOG_DEPRECATIONS=false
  default_module_install_opts:
    ignore-dependencies: ~
    force: ~
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  packages:
    - cron
  # TODO: Remove once using stdlib::to_yaml
  docker_env:
    - STDLIB_LOG_DEPRECATIONS=false
  default_module_install_opts:
    ignore-dependencies: ~
    force: ~
spec/acceptance/nodesets/ubuntu-2204.yml:
  packages:
    - cron
  # TODO: Remove once using stdlib::to_yaml
  docker_env:
    - STDLIB_LOG_DEPRECATIONS=false
  default_module_install_opts:
    ignore-dependencies: ~
    force: ~
